### ISSUE TITLE
회원가입 에러 (signup error)

### ISSUE THREAD

**Issue by jcpark3797** [IoTKETI/mobius-open-platform#141]
가이드라인에 따라 설치를 완료했는데 2가지 issue가 있었습니다.
1. open platform > npm install 에서 아래 오류가 뜸
[06:47:17] The following tasks did not complete: npmInstall
[06:47:17] Did you forget to signal async completion?

2. 회원가입 error 
1번과 같이 에러가 뜸에도 서비스 시작은 정상적으로 되어 웹도 떴는데, 백단 어디에 문제가 있는지 409 Conflict 가 뜹니다.
<pm2 logs> 회원가입 버튼 클릭시 발생하는 오류메시지
3|sns  | Error: Failed to lookup view "error" in views directory "/home/ubuntu/branch-lastest/mobius-open-platform-develop/views"
3|sns  |     at Function.render (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/application.js:580:17)
3|sns  |     at ServerResponse.render (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/response.js:1008:7)
3|sns  |     at /home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/app.js:56:7
3|sns  |     at Layer.handle_error (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/layer.js:71:5)
3|sns  |     at trim_prefix (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:315:13)
3|sns  |     at /home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:284:7
3|sns  |     at Function.process_params (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:335:12)
3|sns  |     at next (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:275:10)
3|sns  |     at Layer.handle_error (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/layer.js:67:12)
3|sns  |     at trim_prefix (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:315:13)
3|sns  |     at /home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:284:7
3|sns  |     at Function.process_params (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:335:12)
3|sns  |     at next (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:275:10)
3|sns  |     at Layer.handle_error (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/layer.js:67:12)
3|sns  |     at trim_prefix (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:315:13)
3|sns  |     at /home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:284:7
3|sns  |     at Function.process_params (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:335:12)
3|sns  |     at next (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:275:10)
3|sns  |     at Layer.handle_error (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/layer.js:67:12)
3|sns  |     at trim_prefix (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:315:13)
3|sns  |     at /home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:284:7
3|sns  |     at Function.process_params (/home/ubuntu/branch-lastest/mobius-open-platform-develop/sns_agent_manage_tool/node_modules/express/lib/router/index.js:335:12)

(node:4473) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and                                                                                                           Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
mobius_webportal already exist
dashboard already exist
OTA_Assist already exist
Bot_Mgmt already exist
Mongodb : Setting > All database has done setting Successfully
[06:46:53] Finished 'setDatabase' after 2.2 s
[06:46:53] Starting 'npmInstall'...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 818 packages in 8.468s

27 packages are looking for funding
  run `npm fund` for details

found 103 vulnerabilities (13 low, 39 moderate, 37 high, 14 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
audited 332 packages in 3.388s

1 package is looking for funding
  run `npm fund` for details

found 62 vulnerabilities (32 moderate, 21 high, 9 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
audited 265 packages in 2.445s
found 46 vulnerabilities (13 moderate, 22 high, 11 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
audited 319 packages in 2.626s
found 71 vulnerabilities (25 moderate, 29 high, 17 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
audited 262 packages in 2.245s

11 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (3 moderate, 2 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
[06:47:17] The following tasks did not complete: npmInstall
[06:47:17] Did you forget to signal async completion?

mobius-open-platform$ gulp serviceRestart
[06:47:52] Using gulpfile ~/mobius-open-platform/gulpfile.js
[06:47:52] Starting 'serviceRestart'...
pm2 res$ pm2 restart webportal dashboard ota sns
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [webportal](ids: [ 0 ])
[PM2] [webportal](0) ✓
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [dashboard](ids: [ 1 ])
[PM2] [dashboard](1) ✓
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [ota](ids: [ 2 ])
[PM2] [ota](2) ✓
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [sns](ids: [ 3 ])
[PM2] [sns](3) ✓
┌─────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ dashboard    │ default     │ 0.0.1   │ fork    │ 4587     │ 0s     │ 14   │ online    │ 35%      │ 35.8mb   │ ubuntu   │ disabled │
│ 2   │ ota          │ default     │ 1.1.0   │ fork    │ 4604     │ 0s     │ 14   │ online    │ 25%      │ 29.6mb   │ ubuntu   │ disabled │
│ 4   │ res          │ default     │ 0.0.0   │ fork    │ 4412     │ 3m     │ 2    │ online    │ 0%       │ 51.9mb   │ ubuntu   │ disabled │
│ 3   │ sns          │ default     │ 1.2.2   │ fork    │ 4617     │ 0s     │ 14   │ online    │ 0%       │ 11.5mb   │ ubuntu   │ disabled │
│ 0   │ webportal    │ default     │ 0.0.1   │ fork    │ 4572     │ 0s     │ 14   │ online    │ 90%      │ 50.8mb   │ ubuntu   │ disabled │
└─────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[06:47:53] Finished 'serviceRestart' after 1.01 s
ubuntu@harbor-test:~/mobius-open-platform$ pm2 restart res
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [res](ids: [ 4 ])
[PM2] [res](4) ✓
┌─────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ dashboard    │ default     │ 0.0.1   │ fork    │ 4587     │ 2s     │ 14   │ online    │ 41.2%    │ 84.4mb   │ ubuntu   │ disabled │
│ 2   │ ota          │ default     │ 1.1.0   │ fork    │ 4604     │ 2s     │ 14   │ online    │ 76.5%    │ 80.8mb   │ ubuntu   │ disabled │
│ 4   │ res          │ default     │ 0.0.0   │ fork    │ 4658     │ 0s     │ 3    │ online    │ 0%       │ 11.6mb   │ ubuntu   │ disabled │
│ 3   │ sns          │ default     │ 1.2.2   │ fork    │ 4617     │ 2s     │ 14   │ online    │ 47.1%    │ 70.5mb   │ ubuntu   │ disabled │
│ 0   │ webportal    │ default     │ 0.0.1   │ fork    │ 4572     │ 3s     │ 14   │ online    │ 0%       │ 88.9mb   │ ubuntu   │ disabled │
└─────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
ubuntu@harbor-test:~/mobius-open-platform$ gulp serviceRestart
[06:47:59] Using gulpfile ~/mobius-open-platform/gulpfile.js
[06:47:59] Starting 'serviceRestart'...
$ pm2 restart webportal dashboard ota sns
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [webportal](ids: [ 0 ])
[PM2] [webportal](0) ✓
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [dashboard](ids: [ 1 ])

**Comment by Sangyong-Jeon** [comment]
1번 과정이 제대로 진행되지 않아서 2번에서 DB와 제대로 연동안되는 걸로 알고 있습니다. 

### 1번 에러 해결방법
gulpfile.js 파일의 `npmInstall()` 함수에서 비동기 작업이 완료되지 않았기 때문에 발생하는 에러로 콜백함수를 호출하거나 Promis, async 을 사용하면 된다고 했지만 저는 전부 실패했습니다. 

그래서 `npmInstall()` 함수 마지막에 `resolve()` 를 넣는것으로 해결했습니다.

### 2번 에러 해결방법

1번을 해결했다면 이후 DB와 연동이 잘 되었기에 회원가입이 정상적으로 될 것입니다.

저도 1번 과정에서 jcpark3797님처럼 무시하고 진행하니까 회원가입이 제대로 안되었는데 해결하고 나니까 잘 되고 있습니다.
